name: deploy CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      run: |
       git config --global user.email "radzim_ko@wp.pl"
       git config --global user.name "Radzim Kowalow"
       npm install
       npm run build
       cd ./docs/.vuepress/dist
       git init
       git add -A
       git commit -m "deploy"
      env:
        BASE_URL: "/data-science-quizzes/"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.deploy_gh }}
        branch: gh-pages
        force: true
