name: deploy CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - run: cd ./docs/.vuepress/dist
    - run: git init
    - run: git add -A
    - run: git commit -m "deploy"
    - run: git push -f https://$(TOKEN)@github.com:RaRhAeu/data-science-quizzes.git master:gh-pages
      env:
        BASE_URL: "/data-science-quizzes/"
        TOKEN: ${{ secrets.deploy_gh }}
