name: deploy CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
      env:
        BASE_URL: "/data-science-quizzes/"
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Configure git
      run: |
        cd ./docs/.vuepress/dist
        git init
        git add -A
        git commit -m "deploy"
        git config --global user.email "radzim_ko@wp.pl"
        git config --global user.name "Radzim Kowalow"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.deploy_gh }}
        branch: gh-pages
        force: true
